// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// KebabShop is the predicate function for kebabshop builders.
type KebabShop func(*sql.Selector)

// TwitchUser is the predicate function for twitchuser builders.
type TwitchUser func(*sql.Selector)
