// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KebabShopDelete is the builder for deleting a KebabShop entity.
type KebabShopDelete struct {
	config
	hooks    []Hook
	mutation *KebabShopMutation
}

// Where appends a list predicates to the KebabShopDelete builder.
func (ksd *KebabShopDelete) Where(ps ...predicate.KebabShop) *KebabShopDelete {
	ksd.mutation.Where(ps...)
	return ksd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ksd *KebabShopDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ksd.hooks) == 0 {
		affected, err = ksd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KebabShopMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ksd.mutation = mutation
			affected, err = ksd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ksd.hooks) - 1; i >= 0; i-- {
			if ksd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ksd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ksd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ksd *KebabShopDelete) ExecX(ctx context.Context) int {
	n, err := ksd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ksd *KebabShopDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: kebabshop.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: kebabshop.FieldID,
			},
		},
	}
	if ps := ksd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ksd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// KebabShopDeleteOne is the builder for deleting a single KebabShop entity.
type KebabShopDeleteOne struct {
	ksd *KebabShopDelete
}

// Exec executes the deletion query.
func (ksdo *KebabShopDeleteOne) Exec(ctx context.Context) error {
	n, err := ksdo.ksd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{kebabshop.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ksdo *KebabShopDeleteOne) ExecX(ctx context.Context) {
	ksdo.ksd.ExecX(ctx)
}
