// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// KebabShop is the model entity for the KebabShop schema.
type KebabShop struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// OsmID holds the value of the "osm_id" field.
	OsmID *int `json:"osm_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Lat holds the value of the "lat" field.
	Lat float64 `json:"lat,omitempty"`
	// Lng holds the value of the "lng" field.
	Lng float64 `json:"lng,omitempty"`
	// Visible holds the value of the "visible" field.
	Visible bool `json:"visible,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KebabShopQuery when eager-loading is set.
	Edges KebabShopEdges `json:"edges"`
}

// KebabShopEdges holds the relations/edges for other nodes in the graph.
type KebabShopEdges struct {
	// UserScores holds the value of the user_scores edge.
	UserScores []*ScoreRating `json:"user_scores,omitempty"`
	// UserPrices holds the value of the user_prices edge.
	UserPrices []*ShopPrice `json:"user_prices,omitempty"`
	// UserOpinions holds the value of the user_opinions edge.
	UserOpinions []*UserOpinion `json:"user_opinions,omitempty"`
	// SubmittedBy holds the value of the submitted_by edge.
	SubmittedBy []*TwitchUser `json:"submitted_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserScoresOrErr returns the UserScores value or an error if the edge
// was not loaded in eager-loading.
func (e KebabShopEdges) UserScoresOrErr() ([]*ScoreRating, error) {
	if e.loadedTypes[0] {
		return e.UserScores, nil
	}
	return nil, &NotLoadedError{edge: "user_scores"}
}

// UserPricesOrErr returns the UserPrices value or an error if the edge
// was not loaded in eager-loading.
func (e KebabShopEdges) UserPricesOrErr() ([]*ShopPrice, error) {
	if e.loadedTypes[1] {
		return e.UserPrices, nil
	}
	return nil, &NotLoadedError{edge: "user_prices"}
}

// UserOpinionsOrErr returns the UserOpinions value or an error if the edge
// was not loaded in eager-loading.
func (e KebabShopEdges) UserOpinionsOrErr() ([]*UserOpinion, error) {
	if e.loadedTypes[2] {
		return e.UserOpinions, nil
	}
	return nil, &NotLoadedError{edge: "user_opinions"}
}

// SubmittedByOrErr returns the SubmittedBy value or an error if the edge
// was not loaded in eager-loading.
func (e KebabShopEdges) SubmittedByOrErr() ([]*TwitchUser, error) {
	if e.loadedTypes[3] {
		return e.SubmittedBy, nil
	}
	return nil, &NotLoadedError{edge: "submitted_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KebabShop) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case kebabshop.FieldVisible:
			values[i] = new(sql.NullBool)
		case kebabshop.FieldLat, kebabshop.FieldLng:
			values[i] = new(sql.NullFloat64)
		case kebabshop.FieldID, kebabshop.FieldOsmID:
			values[i] = new(sql.NullInt64)
		case kebabshop.FieldName:
			values[i] = new(sql.NullString)
		case kebabshop.FieldCreated:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type KebabShop", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KebabShop fields.
func (ks *KebabShop) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kebabshop.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ks.ID = uint64(value.Int64)
		case kebabshop.FieldOsmID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field osm_id", values[i])
			} else if value.Valid {
				ks.OsmID = new(int)
				*ks.OsmID = int(value.Int64)
			}
		case kebabshop.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ks.Name = value.String
			}
		case kebabshop.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				ks.Created = value.Time
			}
		case kebabshop.FieldLat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field lat", values[i])
			} else if value.Valid {
				ks.Lat = value.Float64
			}
		case kebabshop.FieldLng:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field lng", values[i])
			} else if value.Valid {
				ks.Lng = value.Float64
			}
		case kebabshop.FieldVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field visible", values[i])
			} else if value.Valid {
				ks.Visible = value.Bool
			}
		}
	}
	return nil
}

// QueryUserScores queries the "user_scores" edge of the KebabShop entity.
func (ks *KebabShop) QueryUserScores() *ScoreRatingQuery {
	return (&KebabShopClient{config: ks.config}).QueryUserScores(ks)
}

// QueryUserPrices queries the "user_prices" edge of the KebabShop entity.
func (ks *KebabShop) QueryUserPrices() *ShopPriceQuery {
	return (&KebabShopClient{config: ks.config}).QueryUserPrices(ks)
}

// QueryUserOpinions queries the "user_opinions" edge of the KebabShop entity.
func (ks *KebabShop) QueryUserOpinions() *UserOpinionQuery {
	return (&KebabShopClient{config: ks.config}).QueryUserOpinions(ks)
}

// QuerySubmittedBy queries the "submitted_by" edge of the KebabShop entity.
func (ks *KebabShop) QuerySubmittedBy() *TwitchUserQuery {
	return (&KebabShopClient{config: ks.config}).QuerySubmittedBy(ks)
}

// Update returns a builder for updating this KebabShop.
// Note that you need to call KebabShop.Unwrap() before calling this method if this KebabShop
// was returned from a transaction, and the transaction was committed or rolled back.
func (ks *KebabShop) Update() *KebabShopUpdateOne {
	return (&KebabShopClient{config: ks.config}).UpdateOne(ks)
}

// Unwrap unwraps the KebabShop entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ks *KebabShop) Unwrap() *KebabShop {
	_tx, ok := ks.config.driver.(*txDriver)
	if !ok {
		panic("ent: KebabShop is not a transactional entity")
	}
	ks.config.driver = _tx.drv
	return ks
}

// String implements the fmt.Stringer.
func (ks *KebabShop) String() string {
	var builder strings.Builder
	builder.WriteString("KebabShop(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ks.ID))
	if v := ks.OsmID; v != nil {
		builder.WriteString("osm_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ks.Name)
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(ks.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("lat=")
	builder.WriteString(fmt.Sprintf("%v", ks.Lat))
	builder.WriteString(", ")
	builder.WriteString("lng=")
	builder.WriteString(fmt.Sprintf("%v", ks.Lng))
	builder.WriteString(", ")
	builder.WriteString("visible=")
	builder.WriteString(fmt.Sprintf("%v", ks.Visible))
	builder.WriteByte(')')
	return builder.String()
}

// KebabShops is a parsable slice of KebabShop.
type KebabShops []*KebabShop

func (ks KebabShops) config(cfg config) {
	for _i := range ks {
		ks[_i].config = cfg
	}
}
