// Code generated by ent, DO NOT EDIT.

package ent

import (
	"rvnx_doener_service/ent/event"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreated is the schema descriptor for created field.
	eventDescCreated := eventFields[0].Descriptor()
	// event.DefaultCreated holds the default value on creation for the created field.
	event.DefaultCreated = eventDescCreated.Default.(func() time.Time)
	kebabshopFields := schema.KebabShop{}.Fields()
	_ = kebabshopFields
	// kebabshopDescCreated is the schema descriptor for created field.
	kebabshopDescCreated := kebabshopFields[2].Descriptor()
	// kebabshop.DefaultCreated holds the default value on creation for the created field.
	kebabshop.DefaultCreated = kebabshopDescCreated.Default.(func() time.Time)
}
