// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/predicate"
	"rvnx_doener_service/ent/scorerating"
	"rvnx_doener_service/ent/twitchuser"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoreRatingUpdate is the builder for updating ScoreRating entities.
type ScoreRatingUpdate struct {
	config
	hooks    []Hook
	mutation *ScoreRatingMutation
}

// Where appends a list predicates to the ScoreRatingUpdate builder.
func (sru *ScoreRatingUpdate) Where(ps ...predicate.ScoreRating) *ScoreRatingUpdate {
	sru.mutation.Where(ps...)
	return sru
}

// SetScore sets the "score" field.
func (sru *ScoreRatingUpdate) SetScore(f float64) *ScoreRatingUpdate {
	sru.mutation.ResetScore()
	sru.mutation.SetScore(f)
	return sru
}

// AddScore adds f to the "score" field.
func (sru *ScoreRatingUpdate) AddScore(f float64) *ScoreRatingUpdate {
	sru.mutation.AddScore(f)
	return sru
}

// SetAnonymous sets the "anonymous" field.
func (sru *ScoreRatingUpdate) SetAnonymous(b bool) *ScoreRatingUpdate {
	sru.mutation.SetAnonymous(b)
	return sru
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (sru *ScoreRatingUpdate) SetNillableAnonymous(b *bool) *ScoreRatingUpdate {
	if b != nil {
		sru.SetAnonymous(*b)
	}
	return sru
}

// SetShopID sets the "shop" edge to the KebabShop entity by ID.
func (sru *ScoreRatingUpdate) SetShopID(id uint64) *ScoreRatingUpdate {
	sru.mutation.SetShopID(id)
	return sru
}

// SetNillableShopID sets the "shop" edge to the KebabShop entity by ID if the given value is not nil.
func (sru *ScoreRatingUpdate) SetNillableShopID(id *uint64) *ScoreRatingUpdate {
	if id != nil {
		sru = sru.SetShopID(*id)
	}
	return sru
}

// SetShop sets the "shop" edge to the KebabShop entity.
func (sru *ScoreRatingUpdate) SetShop(k *KebabShop) *ScoreRatingUpdate {
	return sru.SetShopID(k.ID)
}

// SetAuthorID sets the "author" edge to the TwitchUser entity by ID.
func (sru *ScoreRatingUpdate) SetAuthorID(id int64) *ScoreRatingUpdate {
	sru.mutation.SetAuthorID(id)
	return sru
}

// SetNillableAuthorID sets the "author" edge to the TwitchUser entity by ID if the given value is not nil.
func (sru *ScoreRatingUpdate) SetNillableAuthorID(id *int64) *ScoreRatingUpdate {
	if id != nil {
		sru = sru.SetAuthorID(*id)
	}
	return sru
}

// SetAuthor sets the "author" edge to the TwitchUser entity.
func (sru *ScoreRatingUpdate) SetAuthor(t *TwitchUser) *ScoreRatingUpdate {
	return sru.SetAuthorID(t.ID)
}

// Mutation returns the ScoreRatingMutation object of the builder.
func (sru *ScoreRatingUpdate) Mutation() *ScoreRatingMutation {
	return sru.mutation
}

// ClearShop clears the "shop" edge to the KebabShop entity.
func (sru *ScoreRatingUpdate) ClearShop() *ScoreRatingUpdate {
	sru.mutation.ClearShop()
	return sru
}

// ClearAuthor clears the "author" edge to the TwitchUser entity.
func (sru *ScoreRatingUpdate) ClearAuthor() *ScoreRatingUpdate {
	sru.mutation.ClearAuthor()
	return sru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sru *ScoreRatingUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sru.hooks) == 0 {
		if err = sru.check(); err != nil {
			return 0, err
		}
		affected, err = sru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScoreRatingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sru.check(); err != nil {
				return 0, err
			}
			sru.mutation = mutation
			affected, err = sru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sru.hooks) - 1; i >= 0; i-- {
			if sru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sru *ScoreRatingUpdate) SaveX(ctx context.Context) int {
	affected, err := sru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sru *ScoreRatingUpdate) Exec(ctx context.Context) error {
	_, err := sru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sru *ScoreRatingUpdate) ExecX(ctx context.Context) {
	if err := sru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sru *ScoreRatingUpdate) check() error {
	if v, ok := sru.mutation.Score(); ok {
		if err := scorerating.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "ScoreRating.score": %w`, err)}
		}
	}
	return nil
}

func (sru *ScoreRatingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scorerating.Table,
			Columns: scorerating.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: scorerating.FieldID,
			},
		},
	}
	if ps := sru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sru.mutation.Score(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: scorerating.FieldScore,
		})
	}
	if value, ok := sru.mutation.AddedScore(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: scorerating.FieldScore,
		})
	}
	if value, ok := sru.mutation.Anonymous(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: scorerating.FieldAnonymous,
		})
	}
	if sru.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.ShopTable,
			Columns: []string{scorerating.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sru.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.ShopTable,
			Columns: []string{scorerating.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sru.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.AuthorTable,
			Columns: []string{scorerating.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sru.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.AuthorTable,
			Columns: []string{scorerating.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scorerating.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ScoreRatingUpdateOne is the builder for updating a single ScoreRating entity.
type ScoreRatingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScoreRatingMutation
}

// SetScore sets the "score" field.
func (sruo *ScoreRatingUpdateOne) SetScore(f float64) *ScoreRatingUpdateOne {
	sruo.mutation.ResetScore()
	sruo.mutation.SetScore(f)
	return sruo
}

// AddScore adds f to the "score" field.
func (sruo *ScoreRatingUpdateOne) AddScore(f float64) *ScoreRatingUpdateOne {
	sruo.mutation.AddScore(f)
	return sruo
}

// SetAnonymous sets the "anonymous" field.
func (sruo *ScoreRatingUpdateOne) SetAnonymous(b bool) *ScoreRatingUpdateOne {
	sruo.mutation.SetAnonymous(b)
	return sruo
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (sruo *ScoreRatingUpdateOne) SetNillableAnonymous(b *bool) *ScoreRatingUpdateOne {
	if b != nil {
		sruo.SetAnonymous(*b)
	}
	return sruo
}

// SetShopID sets the "shop" edge to the KebabShop entity by ID.
func (sruo *ScoreRatingUpdateOne) SetShopID(id uint64) *ScoreRatingUpdateOne {
	sruo.mutation.SetShopID(id)
	return sruo
}

// SetNillableShopID sets the "shop" edge to the KebabShop entity by ID if the given value is not nil.
func (sruo *ScoreRatingUpdateOne) SetNillableShopID(id *uint64) *ScoreRatingUpdateOne {
	if id != nil {
		sruo = sruo.SetShopID(*id)
	}
	return sruo
}

// SetShop sets the "shop" edge to the KebabShop entity.
func (sruo *ScoreRatingUpdateOne) SetShop(k *KebabShop) *ScoreRatingUpdateOne {
	return sruo.SetShopID(k.ID)
}

// SetAuthorID sets the "author" edge to the TwitchUser entity by ID.
func (sruo *ScoreRatingUpdateOne) SetAuthorID(id int64) *ScoreRatingUpdateOne {
	sruo.mutation.SetAuthorID(id)
	return sruo
}

// SetNillableAuthorID sets the "author" edge to the TwitchUser entity by ID if the given value is not nil.
func (sruo *ScoreRatingUpdateOne) SetNillableAuthorID(id *int64) *ScoreRatingUpdateOne {
	if id != nil {
		sruo = sruo.SetAuthorID(*id)
	}
	return sruo
}

// SetAuthor sets the "author" edge to the TwitchUser entity.
func (sruo *ScoreRatingUpdateOne) SetAuthor(t *TwitchUser) *ScoreRatingUpdateOne {
	return sruo.SetAuthorID(t.ID)
}

// Mutation returns the ScoreRatingMutation object of the builder.
func (sruo *ScoreRatingUpdateOne) Mutation() *ScoreRatingMutation {
	return sruo.mutation
}

// ClearShop clears the "shop" edge to the KebabShop entity.
func (sruo *ScoreRatingUpdateOne) ClearShop() *ScoreRatingUpdateOne {
	sruo.mutation.ClearShop()
	return sruo
}

// ClearAuthor clears the "author" edge to the TwitchUser entity.
func (sruo *ScoreRatingUpdateOne) ClearAuthor() *ScoreRatingUpdateOne {
	sruo.mutation.ClearAuthor()
	return sruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sruo *ScoreRatingUpdateOne) Select(field string, fields ...string) *ScoreRatingUpdateOne {
	sruo.fields = append([]string{field}, fields...)
	return sruo
}

// Save executes the query and returns the updated ScoreRating entity.
func (sruo *ScoreRatingUpdateOne) Save(ctx context.Context) (*ScoreRating, error) {
	var (
		err  error
		node *ScoreRating
	)
	if len(sruo.hooks) == 0 {
		if err = sruo.check(); err != nil {
			return nil, err
		}
		node, err = sruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScoreRatingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sruo.check(); err != nil {
				return nil, err
			}
			sruo.mutation = mutation
			node, err = sruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sruo.hooks) - 1; i >= 0; i-- {
			if sruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, sruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ScoreRating)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ScoreRatingMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sruo *ScoreRatingUpdateOne) SaveX(ctx context.Context) *ScoreRating {
	node, err := sruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sruo *ScoreRatingUpdateOne) Exec(ctx context.Context) error {
	_, err := sruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sruo *ScoreRatingUpdateOne) ExecX(ctx context.Context) {
	if err := sruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sruo *ScoreRatingUpdateOne) check() error {
	if v, ok := sruo.mutation.Score(); ok {
		if err := scorerating.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "ScoreRating.score": %w`, err)}
		}
	}
	return nil
}

func (sruo *ScoreRatingUpdateOne) sqlSave(ctx context.Context) (_node *ScoreRating, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scorerating.Table,
			Columns: scorerating.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: scorerating.FieldID,
			},
		},
	}
	id, ok := sruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScoreRating.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scorerating.FieldID)
		for _, f := range fields {
			if !scorerating.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scorerating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sruo.mutation.Score(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: scorerating.FieldScore,
		})
	}
	if value, ok := sruo.mutation.AddedScore(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: scorerating.FieldScore,
		})
	}
	if value, ok := sruo.mutation.Anonymous(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: scorerating.FieldAnonymous,
		})
	}
	if sruo.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.ShopTable,
			Columns: []string{scorerating.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sruo.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.ShopTable,
			Columns: []string{scorerating.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sruo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.AuthorTable,
			Columns: []string{scorerating.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sruo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.AuthorTable,
			Columns: []string{scorerating.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScoreRating{config: sruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scorerating.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
