// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/scorerating"
	"rvnx_doener_service/ent/twitchuser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoreRatingCreate is the builder for creating a ScoreRating entity.
type ScoreRatingCreate struct {
	config
	mutation *ScoreRatingMutation
	hooks    []Hook
}

// SetCreated sets the "created" field.
func (src *ScoreRatingCreate) SetCreated(t time.Time) *ScoreRatingCreate {
	src.mutation.SetCreated(t)
	return src
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (src *ScoreRatingCreate) SetNillableCreated(t *time.Time) *ScoreRatingCreate {
	if t != nil {
		src.SetCreated(*t)
	}
	return src
}

// SetScore sets the "score" field.
func (src *ScoreRatingCreate) SetScore(f float64) *ScoreRatingCreate {
	src.mutation.SetScore(f)
	return src
}

// SetAnonymous sets the "anonymous" field.
func (src *ScoreRatingCreate) SetAnonymous(b bool) *ScoreRatingCreate {
	src.mutation.SetAnonymous(b)
	return src
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (src *ScoreRatingCreate) SetNillableAnonymous(b *bool) *ScoreRatingCreate {
	if b != nil {
		src.SetAnonymous(*b)
	}
	return src
}

// SetID sets the "id" field.
func (src *ScoreRatingCreate) SetID(u uint64) *ScoreRatingCreate {
	src.mutation.SetID(u)
	return src
}

// SetShopID sets the "shop" edge to the KebabShop entity by ID.
func (src *ScoreRatingCreate) SetShopID(id uint64) *ScoreRatingCreate {
	src.mutation.SetShopID(id)
	return src
}

// SetNillableShopID sets the "shop" edge to the KebabShop entity by ID if the given value is not nil.
func (src *ScoreRatingCreate) SetNillableShopID(id *uint64) *ScoreRatingCreate {
	if id != nil {
		src = src.SetShopID(*id)
	}
	return src
}

// SetShop sets the "shop" edge to the KebabShop entity.
func (src *ScoreRatingCreate) SetShop(k *KebabShop) *ScoreRatingCreate {
	return src.SetShopID(k.ID)
}

// SetAuthorID sets the "author" edge to the TwitchUser entity by ID.
func (src *ScoreRatingCreate) SetAuthorID(id int64) *ScoreRatingCreate {
	src.mutation.SetAuthorID(id)
	return src
}

// SetNillableAuthorID sets the "author" edge to the TwitchUser entity by ID if the given value is not nil.
func (src *ScoreRatingCreate) SetNillableAuthorID(id *int64) *ScoreRatingCreate {
	if id != nil {
		src = src.SetAuthorID(*id)
	}
	return src
}

// SetAuthor sets the "author" edge to the TwitchUser entity.
func (src *ScoreRatingCreate) SetAuthor(t *TwitchUser) *ScoreRatingCreate {
	return src.SetAuthorID(t.ID)
}

// Mutation returns the ScoreRatingMutation object of the builder.
func (src *ScoreRatingCreate) Mutation() *ScoreRatingMutation {
	return src.mutation
}

// Save creates the ScoreRating in the database.
func (src *ScoreRatingCreate) Save(ctx context.Context) (*ScoreRating, error) {
	var (
		err  error
		node *ScoreRating
	)
	if err := src.defaults(); err != nil {
		return nil, err
	}
	if len(src.hooks) == 0 {
		if err = src.check(); err != nil {
			return nil, err
		}
		node, err = src.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScoreRatingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = src.check(); err != nil {
				return nil, err
			}
			src.mutation = mutation
			if node, err = src.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(src.hooks) - 1; i >= 0; i-- {
			if src.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = src.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, src.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ScoreRating)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ScoreRatingMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (src *ScoreRatingCreate) SaveX(ctx context.Context) *ScoreRating {
	v, err := src.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (src *ScoreRatingCreate) Exec(ctx context.Context) error {
	_, err := src.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (src *ScoreRatingCreate) ExecX(ctx context.Context) {
	if err := src.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (src *ScoreRatingCreate) defaults() error {
	if _, ok := src.mutation.Created(); !ok {
		if scorerating.DefaultCreated == nil {
			return fmt.Errorf("ent: uninitialized scorerating.DefaultCreated (forgotten import ent/runtime?)")
		}
		v := scorerating.DefaultCreated()
		src.mutation.SetCreated(v)
	}
	if _, ok := src.mutation.Anonymous(); !ok {
		v := scorerating.DefaultAnonymous
		src.mutation.SetAnonymous(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (src *ScoreRatingCreate) check() error {
	if _, ok := src.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "ScoreRating.created"`)}
	}
	if _, ok := src.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "ScoreRating.score"`)}
	}
	if v, ok := src.mutation.Score(); ok {
		if err := scorerating.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "ScoreRating.score": %w`, err)}
		}
	}
	if _, ok := src.mutation.Anonymous(); !ok {
		return &ValidationError{Name: "anonymous", err: errors.New(`ent: missing required field "ScoreRating.anonymous"`)}
	}
	return nil
}

func (src *ScoreRatingCreate) sqlSave(ctx context.Context) (*ScoreRating, error) {
	_node, _spec := src.createSpec()
	if err := sqlgraph.CreateNode(ctx, src.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (src *ScoreRatingCreate) createSpec() (*ScoreRating, *sqlgraph.CreateSpec) {
	var (
		_node = &ScoreRating{config: src.config}
		_spec = &sqlgraph.CreateSpec{
			Table: scorerating.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: scorerating.FieldID,
			},
		}
	)
	if id, ok := src.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := src.mutation.Created(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: scorerating.FieldCreated,
		})
		_node.Created = value
	}
	if value, ok := src.mutation.Score(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: scorerating.FieldScore,
		})
		_node.Score = value
	}
	if value, ok := src.mutation.Anonymous(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: scorerating.FieldAnonymous,
		})
		_node.Anonymous = value
	}
	if nodes := src.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.ShopTable,
			Columns: []string{scorerating.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.kebab_shop_user_scores = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := src.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scorerating.AuthorTable,
			Columns: []string{scorerating.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.twitch_user_score_ratings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScoreRatingCreateBulk is the builder for creating many ScoreRating entities in bulk.
type ScoreRatingCreateBulk struct {
	config
	builders []*ScoreRatingCreate
}

// Save creates the ScoreRating entities in the database.
func (srcb *ScoreRatingCreateBulk) Save(ctx context.Context) ([]*ScoreRating, error) {
	specs := make([]*sqlgraph.CreateSpec, len(srcb.builders))
	nodes := make([]*ScoreRating, len(srcb.builders))
	mutators := make([]Mutator, len(srcb.builders))
	for i := range srcb.builders {
		func(i int, root context.Context) {
			builder := srcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScoreRatingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, srcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, srcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, srcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (srcb *ScoreRatingCreateBulk) SaveX(ctx context.Context) []*ScoreRating {
	v, err := srcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (srcb *ScoreRatingCreateBulk) Exec(ctx context.Context) error {
	_, err := srcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (srcb *ScoreRatingCreateBulk) ExecX(ctx context.Context) {
	if err := srcb.Exec(ctx); err != nil {
		panic(err)
	}
}
