// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/scorerating"
	"rvnx_doener_service/ent/twitchuser"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ScoreRating is the model entity for the ScoreRating schema.
type ScoreRating struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// Anonymous holds the value of the "anonymous" field.
	Anonymous bool `json:"anonymous,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScoreRatingQuery when eager-loading is set.
	Edges                     ScoreRatingEdges `json:"edges"`
	kebab_shop_user_scores    *uint64
	twitch_user_score_ratings *int64
}

// ScoreRatingEdges holds the relations/edges for other nodes in the graph.
type ScoreRatingEdges struct {
	// Shop holds the value of the shop edge.
	Shop *KebabShop `json:"shop,omitempty"`
	// Author holds the value of the author edge.
	Author *TwitchUser `json:"author,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScoreRatingEdges) ShopOrErr() (*KebabShop, error) {
	if e.loadedTypes[0] {
		if e.Shop == nil {
			// The edge shop was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: kebabshop.Label}
		}
		return e.Shop, nil
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScoreRatingEdges) AuthorOrErr() (*TwitchUser, error) {
	if e.loadedTypes[1] {
		if e.Author == nil {
			// The edge author was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: twitchuser.Label}
		}
		return e.Author, nil
	}
	return nil, &NotLoadedError{edge: "author"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScoreRating) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case scorerating.FieldAnonymous:
			values[i] = new(sql.NullBool)
		case scorerating.FieldScore:
			values[i] = new(sql.NullFloat64)
		case scorerating.FieldID:
			values[i] = new(sql.NullInt64)
		case scorerating.FieldCreated:
			values[i] = new(sql.NullTime)
		case scorerating.ForeignKeys[0]: // kebab_shop_user_scores
			values[i] = new(sql.NullInt64)
		case scorerating.ForeignKeys[1]: // twitch_user_score_ratings
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ScoreRating", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScoreRating fields.
func (sr *ScoreRating) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scorerating.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sr.ID = uint64(value.Int64)
		case scorerating.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				sr.Created = value.Time
			}
		case scorerating.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				sr.Score = value.Float64
			}
		case scorerating.FieldAnonymous:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field anonymous", values[i])
			} else if value.Valid {
				sr.Anonymous = value.Bool
			}
		case scorerating.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field kebab_shop_user_scores", value)
			} else if value.Valid {
				sr.kebab_shop_user_scores = new(uint64)
				*sr.kebab_shop_user_scores = uint64(value.Int64)
			}
		case scorerating.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field twitch_user_score_ratings", value)
			} else if value.Valid {
				sr.twitch_user_score_ratings = new(int64)
				*sr.twitch_user_score_ratings = int64(value.Int64)
			}
		}
	}
	return nil
}

// QueryShop queries the "shop" edge of the ScoreRating entity.
func (sr *ScoreRating) QueryShop() *KebabShopQuery {
	return (&ScoreRatingClient{config: sr.config}).QueryShop(sr)
}

// QueryAuthor queries the "author" edge of the ScoreRating entity.
func (sr *ScoreRating) QueryAuthor() *TwitchUserQuery {
	return (&ScoreRatingClient{config: sr.config}).QueryAuthor(sr)
}

// Update returns a builder for updating this ScoreRating.
// Note that you need to call ScoreRating.Unwrap() before calling this method if this ScoreRating
// was returned from a transaction, and the transaction was committed or rolled back.
func (sr *ScoreRating) Update() *ScoreRatingUpdateOne {
	return (&ScoreRatingClient{config: sr.config}).UpdateOne(sr)
}

// Unwrap unwraps the ScoreRating entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sr *ScoreRating) Unwrap() *ScoreRating {
	_tx, ok := sr.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScoreRating is not a transactional entity")
	}
	sr.config.driver = _tx.drv
	return sr
}

// String implements the fmt.Stringer.
func (sr *ScoreRating) String() string {
	var builder strings.Builder
	builder.WriteString("ScoreRating(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sr.ID))
	builder.WriteString("created=")
	builder.WriteString(sr.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", sr.Score))
	builder.WriteString(", ")
	builder.WriteString("anonymous=")
	builder.WriteString(fmt.Sprintf("%v", sr.Anonymous))
	builder.WriteByte(')')
	return builder.String()
}

// ScoreRatings is a parsable slice of ScoreRating.
type ScoreRatings []*ScoreRating

func (sr ScoreRatings) config(cfg config) {
	for _i := range sr {
		sr[_i].config = cfg
	}
}
