// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/predicate"
	"rvnx_doener_service/ent/scorerating"
	"rvnx_doener_service/ent/twitchuser"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoreRatingQuery is the builder for querying ScoreRating entities.
type ScoreRatingQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ScoreRating
	// eager-loading edges.
	withShop   *KebabShopQuery
	withAuthor *TwitchUserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScoreRatingQuery builder.
func (srq *ScoreRatingQuery) Where(ps ...predicate.ScoreRating) *ScoreRatingQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit adds a limit step to the query.
func (srq *ScoreRatingQuery) Limit(limit int) *ScoreRatingQuery {
	srq.limit = &limit
	return srq
}

// Offset adds an offset step to the query.
func (srq *ScoreRatingQuery) Offset(offset int) *ScoreRatingQuery {
	srq.offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *ScoreRatingQuery) Unique(unique bool) *ScoreRatingQuery {
	srq.unique = &unique
	return srq
}

// Order adds an order step to the query.
func (srq *ScoreRatingQuery) Order(o ...OrderFunc) *ScoreRatingQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QueryShop chains the current query on the "shop" edge.
func (srq *ScoreRatingQuery) QueryShop() *KebabShopQuery {
	query := &KebabShopQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scorerating.Table, scorerating.FieldID, selector),
			sqlgraph.To(kebabshop.Table, kebabshop.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scorerating.ShopTable, scorerating.ShopColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuthor chains the current query on the "author" edge.
func (srq *ScoreRatingQuery) QueryAuthor() *TwitchUserQuery {
	query := &TwitchUserQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scorerating.Table, scorerating.FieldID, selector),
			sqlgraph.To(twitchuser.Table, twitchuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scorerating.AuthorTable, scorerating.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScoreRating entity from the query.
// Returns a *NotFoundError when no ScoreRating was found.
func (srq *ScoreRatingQuery) First(ctx context.Context) (*ScoreRating, error) {
	nodes, err := srq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scorerating.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *ScoreRatingQuery) FirstX(ctx context.Context) *ScoreRating {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScoreRating ID from the query.
// Returns a *NotFoundError when no ScoreRating ID was found.
func (srq *ScoreRatingQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scorerating.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *ScoreRatingQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScoreRating entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScoreRating entity is found.
// Returns a *NotFoundError when no ScoreRating entities are found.
func (srq *ScoreRatingQuery) Only(ctx context.Context) (*ScoreRating, error) {
	nodes, err := srq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scorerating.Label}
	default:
		return nil, &NotSingularError{scorerating.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *ScoreRatingQuery) OnlyX(ctx context.Context) *ScoreRating {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScoreRating ID in the query.
// Returns a *NotSingularError when more than one ScoreRating ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *ScoreRatingQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scorerating.Label}
	default:
		err = &NotSingularError{scorerating.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *ScoreRatingQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScoreRatings.
func (srq *ScoreRatingQuery) All(ctx context.Context) ([]*ScoreRating, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return srq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (srq *ScoreRatingQuery) AllX(ctx context.Context) []*ScoreRating {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScoreRating IDs.
func (srq *ScoreRatingQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := srq.Select(scorerating.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *ScoreRatingQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *ScoreRatingQuery) Count(ctx context.Context) (int, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return srq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (srq *ScoreRatingQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *ScoreRatingQuery) Exist(ctx context.Context) (bool, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return srq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *ScoreRatingQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScoreRatingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *ScoreRatingQuery) Clone() *ScoreRatingQuery {
	if srq == nil {
		return nil
	}
	return &ScoreRatingQuery{
		config:     srq.config,
		limit:      srq.limit,
		offset:     srq.offset,
		order:      append([]OrderFunc{}, srq.order...),
		predicates: append([]predicate.ScoreRating{}, srq.predicates...),
		withShop:   srq.withShop.Clone(),
		withAuthor: srq.withAuthor.Clone(),
		// clone intermediate query.
		sql:    srq.sql.Clone(),
		path:   srq.path,
		unique: srq.unique,
	}
}

// WithShop tells the query-builder to eager-load the nodes that are connected to
// the "shop" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *ScoreRatingQuery) WithShop(opts ...func(*KebabShopQuery)) *ScoreRatingQuery {
	query := &KebabShopQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withShop = query
	return srq
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *ScoreRatingQuery) WithAuthor(opts ...func(*TwitchUserQuery)) *ScoreRatingQuery {
	query := &TwitchUserQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withAuthor = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Created time.Time `json:"created,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScoreRating.Query().
//		GroupBy(scorerating.FieldCreated).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (srq *ScoreRatingQuery) GroupBy(field string, fields ...string) *ScoreRatingGroupBy {
	grbuild := &ScoreRatingGroupBy{config: srq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return srq.sqlQuery(ctx), nil
	}
	grbuild.label = scorerating.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Created time.Time `json:"created,omitempty"`
//	}
//
//	client.ScoreRating.Query().
//		Select(scorerating.FieldCreated).
//		Scan(ctx, &v)
func (srq *ScoreRatingQuery) Select(fields ...string) *ScoreRatingSelect {
	srq.fields = append(srq.fields, fields...)
	selbuild := &ScoreRatingSelect{ScoreRatingQuery: srq}
	selbuild.label = scorerating.Label
	selbuild.flds, selbuild.scan = &srq.fields, selbuild.Scan
	return selbuild
}

func (srq *ScoreRatingQuery) prepareQuery(ctx context.Context) error {
	for _, f := range srq.fields {
		if !scorerating.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *ScoreRatingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScoreRating, error) {
	var (
		nodes       = []*ScoreRating{}
		withFKs     = srq.withFKs
		_spec       = srq.querySpec()
		loadedTypes = [2]bool{
			srq.withShop != nil,
			srq.withAuthor != nil,
		}
	)
	if srq.withShop != nil || srq.withAuthor != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, scorerating.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ScoreRating).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ScoreRating{config: srq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := srq.withShop; query != nil {
		ids := make([]uint64, 0, len(nodes))
		nodeids := make(map[uint64][]*ScoreRating)
		for i := range nodes {
			if nodes[i].kebab_shop_user_scores == nil {
				continue
			}
			fk := *nodes[i].kebab_shop_user_scores
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(kebabshop.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "kebab_shop_user_scores" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Shop = n
			}
		}
	}

	if query := srq.withAuthor; query != nil {
		ids := make([]int64, 0, len(nodes))
		nodeids := make(map[int64][]*ScoreRating)
		for i := range nodes {
			if nodes[i].twitch_user_score_ratings == nil {
				continue
			}
			fk := *nodes[i].twitch_user_score_ratings
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(twitchuser.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "twitch_user_score_ratings" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Author = n
			}
		}
	}

	return nodes, nil
}

func (srq *ScoreRatingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	_spec.Node.Columns = srq.fields
	if len(srq.fields) > 0 {
		_spec.Unique = srq.unique != nil && *srq.unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *ScoreRatingQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := srq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (srq *ScoreRatingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scorerating.Table,
			Columns: scorerating.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: scorerating.FieldID,
			},
		},
		From:   srq.sql,
		Unique: true,
	}
	if unique := srq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := srq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scorerating.FieldID)
		for i := range fields {
			if fields[i] != scorerating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *ScoreRatingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(scorerating.Table)
	columns := srq.fields
	if len(columns) == 0 {
		columns = scorerating.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.unique != nil && *srq.unique {
		selector.Distinct()
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScoreRatingGroupBy is the group-by builder for ScoreRating entities.
type ScoreRatingGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *ScoreRatingGroupBy) Aggregate(fns ...AggregateFunc) *ScoreRatingGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the group-by query and scans the result into the given value.
func (srgb *ScoreRatingGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := srgb.path(ctx)
	if err != nil {
		return err
	}
	srgb.sql = query
	return srgb.sqlScan(ctx, v)
}

func (srgb *ScoreRatingGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range srgb.fields {
		if !scorerating.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := srgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (srgb *ScoreRatingGroupBy) sqlQuery() *sql.Selector {
	selector := srgb.sql.Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(srgb.fields)+len(srgb.fns))
		for _, f := range srgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(srgb.fields...)...)
}

// ScoreRatingSelect is the builder for selecting fields of ScoreRating entities.
type ScoreRatingSelect struct {
	*ScoreRatingQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (srs *ScoreRatingSelect) Scan(ctx context.Context, v interface{}) error {
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	srs.sql = srs.ScoreRatingQuery.sqlQuery(ctx)
	return srs.sqlScan(ctx, v)
}

func (srs *ScoreRatingSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := srs.sql.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
