// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rvnx_doener_service/ent/twitchuser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TwitchUserCreate is the builder for creating a TwitchUser entity.
type TwitchUserCreate struct {
	config
	mutation *TwitchUserMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (tuc *TwitchUserCreate) SetLogin(s string) *TwitchUserCreate {
	tuc.mutation.SetLogin(s)
	return tuc
}

// SetEmail sets the "email" field.
func (tuc *TwitchUserCreate) SetEmail(s string) *TwitchUserCreate {
	tuc.mutation.SetEmail(s)
	return tuc
}

// SetDisplayName sets the "display_name" field.
func (tuc *TwitchUserCreate) SetDisplayName(s string) *TwitchUserCreate {
	tuc.mutation.SetDisplayName(s)
	return tuc
}

// SetCreatedAt sets the "created_at" field.
func (tuc *TwitchUserCreate) SetCreatedAt(t time.Time) *TwitchUserCreate {
	tuc.mutation.SetCreatedAt(t)
	return tuc
}

// SetOauthToken sets the "oauth_token" field.
func (tuc *TwitchUserCreate) SetOauthToken(s string) *TwitchUserCreate {
	tuc.mutation.SetOauthToken(s)
	return tuc
}

// SetOauthRefreshToken sets the "oauth_refresh_token" field.
func (tuc *TwitchUserCreate) SetOauthRefreshToken(s string) *TwitchUserCreate {
	tuc.mutation.SetOauthRefreshToken(s)
	return tuc
}

// SetID sets the "id" field.
func (tuc *TwitchUserCreate) SetID(i int64) *TwitchUserCreate {
	tuc.mutation.SetID(i)
	return tuc
}

// Mutation returns the TwitchUserMutation object of the builder.
func (tuc *TwitchUserCreate) Mutation() *TwitchUserMutation {
	return tuc.mutation
}

// Save creates the TwitchUser in the database.
func (tuc *TwitchUserCreate) Save(ctx context.Context) (*TwitchUser, error) {
	var (
		err  error
		node *TwitchUser
	)
	if len(tuc.hooks) == 0 {
		if err = tuc.check(); err != nil {
			return nil, err
		}
		node, err = tuc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TwitchUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tuc.check(); err != nil {
				return nil, err
			}
			tuc.mutation = mutation
			if node, err = tuc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tuc.hooks) - 1; i >= 0; i-- {
			if tuc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tuc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*TwitchUser)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TwitchUserMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tuc *TwitchUserCreate) SaveX(ctx context.Context) *TwitchUser {
	v, err := tuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tuc *TwitchUserCreate) Exec(ctx context.Context) error {
	_, err := tuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuc *TwitchUserCreate) ExecX(ctx context.Context) {
	if err := tuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuc *TwitchUserCreate) check() error {
	if _, ok := tuc.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "TwitchUser.login"`)}
	}
	if _, ok := tuc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "TwitchUser.email"`)}
	}
	if _, ok := tuc.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "TwitchUser.display_name"`)}
	}
	if _, ok := tuc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TwitchUser.created_at"`)}
	}
	if _, ok := tuc.mutation.OauthToken(); !ok {
		return &ValidationError{Name: "oauth_token", err: errors.New(`ent: missing required field "TwitchUser.oauth_token"`)}
	}
	if _, ok := tuc.mutation.OauthRefreshToken(); !ok {
		return &ValidationError{Name: "oauth_refresh_token", err: errors.New(`ent: missing required field "TwitchUser.oauth_refresh_token"`)}
	}
	return nil
}

func (tuc *TwitchUserCreate) sqlSave(ctx context.Context) (*TwitchUser, error) {
	_node, _spec := tuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (tuc *TwitchUserCreate) createSpec() (*TwitchUser, *sqlgraph.CreateSpec) {
	var (
		_node = &TwitchUser{config: tuc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: twitchuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: twitchuser.FieldID,
			},
		}
	)
	if id, ok := tuc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tuc.mutation.Login(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: twitchuser.FieldLogin,
		})
		_node.Login = value
	}
	if value, ok := tuc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: twitchuser.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := tuc.mutation.DisplayName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: twitchuser.FieldDisplayName,
		})
		_node.DisplayName = value
	}
	if value, ok := tuc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: twitchuser.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tuc.mutation.OauthToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: twitchuser.FieldOauthToken,
		})
		_node.OauthToken = value
	}
	if value, ok := tuc.mutation.OauthRefreshToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: twitchuser.FieldOauthRefreshToken,
		})
		_node.OauthRefreshToken = value
	}
	return _node, _spec
}

// TwitchUserCreateBulk is the builder for creating many TwitchUser entities in bulk.
type TwitchUserCreateBulk struct {
	config
	builders []*TwitchUserCreate
}

// Save creates the TwitchUser entities in the database.
func (tucb *TwitchUserCreateBulk) Save(ctx context.Context) ([]*TwitchUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tucb.builders))
	nodes := make([]*TwitchUser, len(tucb.builders))
	mutators := make([]Mutator, len(tucb.builders))
	for i := range tucb.builders {
		func(i int, root context.Context) {
			builder := tucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TwitchUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tucb *TwitchUserCreateBulk) SaveX(ctx context.Context) []*TwitchUser {
	v, err := tucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tucb *TwitchUserCreateBulk) Exec(ctx context.Context) error {
	_, err := tucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tucb *TwitchUserCreateBulk) ExecX(ctx context.Context) {
	if err := tucb.Exec(ctx); err != nil {
		panic(err)
	}
}
