// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rvnx_doener_service/ent/kebabshop"
	"rvnx_doener_service/ent/twitchuser"
	"rvnx_doener_service/ent/useropinion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOpinionCreate is the builder for creating a UserOpinion entity.
type UserOpinionCreate struct {
	config
	mutation *UserOpinionMutation
	hooks    []Hook
}

// SetCreated sets the "created" field.
func (uoc *UserOpinionCreate) SetCreated(t time.Time) *UserOpinionCreate {
	uoc.mutation.SetCreated(t)
	return uoc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (uoc *UserOpinionCreate) SetNillableCreated(t *time.Time) *UserOpinionCreate {
	if t != nil {
		uoc.SetCreated(*t)
	}
	return uoc
}

// SetOpinion sets the "opinion" field.
func (uoc *UserOpinionCreate) SetOpinion(s string) *UserOpinionCreate {
	uoc.mutation.SetOpinion(s)
	return uoc
}

// SetAnonymous sets the "anonymous" field.
func (uoc *UserOpinionCreate) SetAnonymous(b bool) *UserOpinionCreate {
	uoc.mutation.SetAnonymous(b)
	return uoc
}

// SetNillableAnonymous sets the "anonymous" field if the given value is not nil.
func (uoc *UserOpinionCreate) SetNillableAnonymous(b *bool) *UserOpinionCreate {
	if b != nil {
		uoc.SetAnonymous(*b)
	}
	return uoc
}

// SetID sets the "id" field.
func (uoc *UserOpinionCreate) SetID(u uint64) *UserOpinionCreate {
	uoc.mutation.SetID(u)
	return uoc
}

// SetShopID sets the "shop" edge to the KebabShop entity by ID.
func (uoc *UserOpinionCreate) SetShopID(id uint64) *UserOpinionCreate {
	uoc.mutation.SetShopID(id)
	return uoc
}

// SetNillableShopID sets the "shop" edge to the KebabShop entity by ID if the given value is not nil.
func (uoc *UserOpinionCreate) SetNillableShopID(id *uint64) *UserOpinionCreate {
	if id != nil {
		uoc = uoc.SetShopID(*id)
	}
	return uoc
}

// SetShop sets the "shop" edge to the KebabShop entity.
func (uoc *UserOpinionCreate) SetShop(k *KebabShop) *UserOpinionCreate {
	return uoc.SetShopID(k.ID)
}

// SetAuthorID sets the "author" edge to the TwitchUser entity by ID.
func (uoc *UserOpinionCreate) SetAuthorID(id int64) *UserOpinionCreate {
	uoc.mutation.SetAuthorID(id)
	return uoc
}

// SetNillableAuthorID sets the "author" edge to the TwitchUser entity by ID if the given value is not nil.
func (uoc *UserOpinionCreate) SetNillableAuthorID(id *int64) *UserOpinionCreate {
	if id != nil {
		uoc = uoc.SetAuthorID(*id)
	}
	return uoc
}

// SetAuthor sets the "author" edge to the TwitchUser entity.
func (uoc *UserOpinionCreate) SetAuthor(t *TwitchUser) *UserOpinionCreate {
	return uoc.SetAuthorID(t.ID)
}

// Mutation returns the UserOpinionMutation object of the builder.
func (uoc *UserOpinionCreate) Mutation() *UserOpinionMutation {
	return uoc.mutation
}

// Save creates the UserOpinion in the database.
func (uoc *UserOpinionCreate) Save(ctx context.Context) (*UserOpinion, error) {
	var (
		err  error
		node *UserOpinion
	)
	if err := uoc.defaults(); err != nil {
		return nil, err
	}
	if len(uoc.hooks) == 0 {
		if err = uoc.check(); err != nil {
			return nil, err
		}
		node, err = uoc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserOpinionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uoc.check(); err != nil {
				return nil, err
			}
			uoc.mutation = mutation
			if node, err = uoc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uoc.hooks) - 1; i >= 0; i-- {
			if uoc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uoc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, uoc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserOpinion)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserOpinionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uoc *UserOpinionCreate) SaveX(ctx context.Context) *UserOpinion {
	v, err := uoc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uoc *UserOpinionCreate) Exec(ctx context.Context) error {
	_, err := uoc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoc *UserOpinionCreate) ExecX(ctx context.Context) {
	if err := uoc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoc *UserOpinionCreate) defaults() error {
	if _, ok := uoc.mutation.Created(); !ok {
		if useropinion.DefaultCreated == nil {
			return fmt.Errorf("ent: uninitialized useropinion.DefaultCreated (forgotten import ent/runtime?)")
		}
		v := useropinion.DefaultCreated()
		uoc.mutation.SetCreated(v)
	}
	if _, ok := uoc.mutation.Anonymous(); !ok {
		v := useropinion.DefaultAnonymous
		uoc.mutation.SetAnonymous(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uoc *UserOpinionCreate) check() error {
	if _, ok := uoc.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "UserOpinion.created"`)}
	}
	if _, ok := uoc.mutation.Opinion(); !ok {
		return &ValidationError{Name: "opinion", err: errors.New(`ent: missing required field "UserOpinion.opinion"`)}
	}
	if v, ok := uoc.mutation.Opinion(); ok {
		if err := useropinion.OpinionValidator(v); err != nil {
			return &ValidationError{Name: "opinion", err: fmt.Errorf(`ent: validator failed for field "UserOpinion.opinion": %w`, err)}
		}
	}
	if _, ok := uoc.mutation.Anonymous(); !ok {
		return &ValidationError{Name: "anonymous", err: errors.New(`ent: missing required field "UserOpinion.anonymous"`)}
	}
	return nil
}

func (uoc *UserOpinionCreate) sqlSave(ctx context.Context) (*UserOpinion, error) {
	_node, _spec := uoc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uoc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (uoc *UserOpinionCreate) createSpec() (*UserOpinion, *sqlgraph.CreateSpec) {
	var (
		_node = &UserOpinion{config: uoc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: useropinion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: useropinion.FieldID,
			},
		}
	)
	if id, ok := uoc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uoc.mutation.Created(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: useropinion.FieldCreated,
		})
		_node.Created = value
	}
	if value, ok := uoc.mutation.Opinion(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useropinion.FieldOpinion,
		})
		_node.Opinion = value
	}
	if value, ok := uoc.mutation.Anonymous(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: useropinion.FieldAnonymous,
		})
		_node.Anonymous = value
	}
	if nodes := uoc.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useropinion.ShopTable,
			Columns: []string{useropinion.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: kebabshop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.kebab_shop_user_opinions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uoc.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useropinion.AuthorTable,
			Columns: []string{useropinion.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: twitchuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.twitch_user_user_opinions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserOpinionCreateBulk is the builder for creating many UserOpinion entities in bulk.
type UserOpinionCreateBulk struct {
	config
	builders []*UserOpinionCreate
}

// Save creates the UserOpinion entities in the database.
func (uocb *UserOpinionCreateBulk) Save(ctx context.Context) ([]*UserOpinion, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uocb.builders))
	nodes := make([]*UserOpinion, len(uocb.builders))
	mutators := make([]Mutator, len(uocb.builders))
	for i := range uocb.builders {
		func(i int, root context.Context) {
			builder := uocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserOpinionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uocb *UserOpinionCreateBulk) SaveX(ctx context.Context) []*UserOpinion {
	v, err := uocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uocb *UserOpinionCreateBulk) Exec(ctx context.Context) error {
	_, err := uocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uocb *UserOpinionCreateBulk) ExecX(ctx context.Context) {
	if err := uocb.Exec(ctx); err != nil {
		panic(err)
	}
}
