// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "event_type", Type: field.TypeEnum, Enums: []string{"kebab_shop.created", "kebab_shop.imported", "kebab_shop.osm_update"}},
		{Name: "info", Type: field.TypeJSON},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
	}
	// KebabShopsColumns holds the columns for the "kebab_shops" table.
	KebabShopsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "osm_id", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "lat", Type: field.TypeFloat64},
		{Name: "lng", Type: field.TypeFloat64},
	}
	// KebabShopsTable holds the schema information for the "kebab_shops" table.
	KebabShopsTable = &schema.Table{
		Name:       "kebab_shops",
		Columns:    KebabShopsColumns,
		PrimaryKey: []*schema.Column{KebabShopsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "kebabshop_lat",
				Unique:  false,
				Columns: []*schema.Column{KebabShopsColumns[4]},
			},
			{
				Name:    "kebabshop_lng",
				Unique:  false,
				Columns: []*schema.Column{KebabShopsColumns[5]},
			},
			{
				Name:    "kebabshop_name",
				Unique:  false,
				Columns: []*schema.Column{KebabShopsColumns[2]},
			},
			{
				Name:    "kebabshop_osm_id",
				Unique:  false,
				Columns: []*schema.Column{KebabShopsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		KebabShopsTable,
	}
)

func init() {
}
