// Code generated by ent, DO NOT EDIT.

package kebabshop

import (
	"time"
)

const (
	// Label holds the string label denoting the kebabshop type in the database.
	Label = "kebab_shop"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOsmID holds the string denoting the osm_id field in the database.
	FieldOsmID = "osm_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldPoint holds the string denoting the point field in the database.
	FieldPoint = "point"
	// Table holds the table name of the kebabshop in the database.
	Table = "kebab_shops"
)

// Columns holds all SQL columns for kebabshop fields.
var Columns = []string{
	FieldID,
	FieldOsmID,
	FieldName,
	FieldCreated,
	FieldPoint,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
)
