name: Test and build

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: setup go dependency cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go test
        run: |
          cd rvnx_doener_service
          go mod tidy
          ./bin/runTestPostgres
          TEST_DATABASE_URL=postgresql://pg:pg@localhost:5433 go test ./...
          docker stop rvnx_doener_testdb


  build-and-deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          git-push-flags: "--force"
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ secrets.DOKKU_APP_NAME }}